-- 03. INNER JOIN

-- 사원 번호와 사원 이름, 소속부서 코드와 소속부서 이름을 찾기
-- JOIN 조건을 WHERE 절에서 정의
SELECT EMP.DEPTNO, EMPNO, ENAME, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

-- INNER JOIN와 ON 조건절을 사용하여 동일한 조건 찾기
-- JOIN 조건을 FROM 절 이하 ON 절에서 정의
SELECT EMP.DEPTNO, EMPNO, ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- INNER는 Default 옵션으로 생략 가능
SELECT EMP.DEPTNO, EMPNO, ENAME, DNAME
FROM EMP JOIN DEPT
ON EMPNO = DEPT.DEPTNO;

