-- 02. ROLLUP 함수

-- STEP 1. 일반적인 GROUP BY 절 사용
-- 부서명과 업무명을 기준으로 사원수와 급여 합을 집계한 일반적인 GROUP BY SQL 문장을 수행
SELECT DNAME, JOB, COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME, JOB;

-- STEP 1-2. GROUP BY + ORDER BY 사용
-- 부서별, 업무별 정렬
SELECT DNAME, JOB, COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME, JOB
ORDER BY DNAME, JOB;

-- STEP 2. ROLLUP 함수 사용
-- 실행 결과에서 2개의 GROUPING COLUMNS(DNAME, JOB)에 대하여 다음과 같은 추가 LEVEL의 집계가 생성
-- L1 : GROUP BY 수행시 생성되는 표준 집계
-- L2 : DNAME 별 모든 JOB의 SUBTOTAL
-- L3 : GRAND TOTAL
SELECT DNAME, JOB, COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP (DNAME, JOB);   -- 해당 인수의 순서가 바뀌면 결과도 달라짐

-- STEP 2-2. ROLLUP 함수 + ORDER BY 절 사용
SELECT DNAME, JOB, COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP (DNAME, JOB)
ORDER BY DNAME, JOB;

-- STEP 3. GROUPING 함수 사용
-- ROLLUP이나 CUBE 등 새로운 그룹 함수를 지원하기 위한 함수
-- 새로운 그룹 함수에 의해 소계가 계산된 결과에는 GROUPING(EXPR) = 1 표시
-- 그 외의 결과에는 0이 표시
SELECT DNAME, GROUPING(DNAME), JOB, GROUPING(JOB), COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP (DNAME, JOB)
ORDER BY DNAME, JOB;

-- STEP 4. GROUPING 함수 + CASE 사용
SELECT
    CASE GROUPING(DNAME) WHEN 1 THEN 'All Departments' ELSE DNAME END AS DNAME, -- 집계 레코드 구분을 위한 함수
    CASE GROUPING(JOB) WHEN 1 THEN 'All Jobs' ELSE JOB END AS JOB,
    COUNT(*) "Total Empl",
    SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP (DNAME, JOB);

-- STEP 4-2. ROLLUP 함수 일부 사용
-- ROLLUP 함수에서 DNAME은 사용하지 않음
-- ALL DEPARTMENTS 에 대한 계산이 이뤄지지 않는다.
SELECT
    CASE GROUPING(DNAME) WHEN 1 THEN 'All Departments' ELSE DNAME END AS DNAME, -- 집계 레코드 구분을 위한 함수
    CASE GROUPING(JOB) WHEN 1 THEN 'All Jobs' ELSE JOB END AS JOB,
    COUNT(*) "Total Empl",
    SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP (JOB);

-- STEP 4-3. ROLLUP 함수 결합 칼럼 사용
-- JOB과 MGR은 하나의 집합으로 간주하고, 부서별, JOB & MGR에 대한 ROLLUP 결과를 출력한다.
SELECT DNAME, JOB, MGR, SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP (DNAME, (JOB, MGR));