/*
  3. ALTER TABLE
  테이블에 필요한 컬럼을 추가, 삭제 등 변경
*/

-- (1) ADD COLUMN
-- Oracle
ALTER TABLE PLAYER ADD (P_ADDRESS VARCHAR2(80));

-- (2) DROP COLUMN
-- Oracle
ALTER TABLE PLAYER DROP COLUMN P_ADDRESS;

-- (3) MODIFY COLUMN
-- 데이터 유형, 티폴트 값, NOT NULL 제약 조건 변경
-- Oracle
ALTER TABLE TEAM_TEMP MODIFY (ORIG_YYYY VARCHAR2(8) DEFAULT '20020129' NOT NULL);

-- SQL Server
ALTER TABLE TEAM_TEMP ALTER COLUMN ORIG_YYYY VARCHAR(8) NOT NULL;
ALTER TABLE TEAM_TEMP ADD CONSTRAINT DF_ORIG_YYYY '20020129' FOR ORIG_YYYY;

-- (4) RENAME COLUMN
-- COLUMN 이름 변경
ALTER TABLE PLAYER RENAME COLUMN PLAYER_ID TO TEMP_ID;

-- (5) DROP CONSTRAINT
-- 제약조건 삭제
ALTER TABLE PLAYER DROP CONSTRAINT PLAYER_FK;

-- (6) ADD CONSTRAINT
-- 제약조건 추가
ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID);